/*
 * Adapter
 * This is a sample API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: yklesovay@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.prokarma.pkmst.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.prokarma.pkmst.model.ClientCard;
import org.threeten.bp.LocalDate;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.ResponseEntity;
import org.springframework.web.multipart.MultipartFile;

/**
 * API tests for ClientApi
 */
@Ignore
public class ClientApiTest {

    private final ObjectMapper objectMapper = new ObjectMapper();

    private final ClientApi api = new ClientApiController(objectMapper);

    private final String accept = "application/json";

    
    /**
     * Add a new Client Card
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addClientCardTest() throws Exception {
        ClientCard body = null;
    ResponseEntity<Void> response = api.addClientCard(body , accept);

        // TODO: test validations
    }
    
    /**
     * Finds ClientCards by ClientCriteria
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void findClientCardByClientCriteriaTest() throws Exception {
        String name = null;
        String surname = null;
        String parentName = null;
        String typeDoc = null;
        String seriaDoc = null;
        String numDoc = null;
        String issuer = null;
        LocalDate issueDate = null;
    ResponseEntity<List<ClientCard>> response = api.findClientCardByClientCriteria(name, surname, parentName, typeDoc, seriaDoc, numDoc, issuer, issueDate , accept);

        // TODO: test validations
    }
    
    /**
     * Find ClientCard by ID
     *
     * Returns a single ClientCard
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getClientCardByIdTest() throws Exception {
        Long clientCardId = null;
    ResponseEntity<ClientCard> response = api.getClientCardById(clientCardId , accept);

        // TODO: test validations
    }
    
}
